### ISSUE TITLE
Great Come Up!

### ISSUE THREAD

**Issue by mrnelley** [leesandra/homework3#1]
I am so proud of the strides you made in this last week! 
Grading 0-5: 
0 meaning you did not meet the requirements and need help getting to a place of competency
5 meaning you obviously understand the material and are able to meet HW requirements

Comprehension: 5
Completion: 4

Its evident that you have learned a lot this week, and are conquering imposter syndrome with flying colors. How could I give you anything less than a 5 for comprehension?! You've displayed the number one rule of development: This time last week we were having a discussion about what divs do and how to apply styles to an HTML page effectively. Comparing this weeks work to last week, you have made significant strides in becoming a front end developer. That is something I cannot grade you poorly on, because I know that you put in the work to get this far. Keep pushing! ;)

**Comment by leesandra** [comment]
Thanks Nelley! Really appreciate the feed back.
